
INSERT INTO public.bdd_scenarios (scenario_id, feature_area, feature_area_number, title, gherkin, test_type, status)
VALUES
  ('AUTH-ENGINE-001', 'auth-rebuild', 200, 'client_session_write_failed never punishes the user (Vichea invariant)',
   E'Given a member submits valid credentials\nAnd the supabase client throws client_session_write_failed after server auth succeeded\nWhen the engine processes the failure\nThen [Code] decideFailureActions returns incrementDeviceLockout=false, recordCredentialFailureRpc=false, recordServerRateLimitFailure=false\nAnd [DB] no row is appended to login_attempts for the email\nAnd [DB] no row is appended to rate_limits for the email\nAnd [UI] the banner reads "We need to retry sign-in." with no lockout countdown\nAnd [DB] ops_events records auth_engine.client_session_write_failed at severity=info',
   'unit', 'not_built'),
  ('AUTH-ENGINE-002', 'auth-rebuild', 200, 'captcha_failed resets the widget in place without a page refresh',
   E'Given a member submits the sign-in form with an expired Turnstile token\nWhen the engine receives captcha_failed\nThen [Code] the engine clears captchaToken and increments captchaSoftResetCount\nAnd [UI] the Turnstile widget re-mounts with a fresh challenge\nAnd [UI] the form stays enabled (no full-page reload)\nAnd [DB] ops_events records auth_engine.captcha_failed and auth_engine.captcha_reset back-to-back',
   'manual', 'not_built'),
  ('AUTH-ENGINE-003', 'auth-rebuild', 200, 'invalid_credentials increments all three punitive channels',
   E'Given a member submits a wrong password\nWhen the engine receives invalid_credentials\nThen [Code] device lockout counter is incremented (recordInvalidAuthAttempt)\nAnd [Code] captcha failure counter is incremented (recordFailedLoginAttempt)\nAnd [DB] login_attempts gains a row for the email via record_failed_login\nAnd [DB] rate_limits gains a row via RateLimitService.recordFailure\nAnd [UI] a single AuthErrorBanner explains the failure (no double-banner)',
   'manual', 'not_built'),
  ('AUTH-ENGINE-004', 'auth-rebuild', 200, 'google_only_account banner offers Google only and never suggests reset',
   E'Given a member with a google-only identity submits any password\nWhen the engine receives google_only_account\nThen [Code] decideFailureActions returns suggestReset=false\nAnd [UI] the banner shows "Continue with Google" and no "Reset password" link\nAnd [DB] no password-reset email is enqueued',
   'unit', 'not_built'),
  ('AUTH-ENGINE-005', 'auth-rebuild', 200, 'session_expired on reset disables the form and offers a new link',
   E'Given a member opens an expired /reset-password link\nWhen the engine confirms recovery session is invalid\nThen [UI] the password form is disabled\nAnd [UI] a "Request a new reset link" CTA is shown\nAnd [UI] there is no automatic redirect to /login\nAnd [DB] ops_events records auth_engine.reset_failed with code=session_expired',
   'manual', 'not_built'),
  ('AUTH-ENGINE-006', 'auth-rebuild', 200, 'weak_password / same_password / rate_limited come from edge function codes only',
   E'Given the update-password-confirmed edge function returns a typed error code\nWhen the reset engine maps the error\nThen [Code] the AuthFailureReason is derived from the edge response code, never from message string-matching\nAnd [UI] AuthErrorBanner renders the brand-voice copy mapped to that code\nAnd [DB] ops_events records auth_engine.reset_failed with the code',
   'unit', 'not_built'),
  ('AUTH-ENGINE-007', 'auth-rebuild', 200, 'Password-reset success clears every counter in one place',
   E'Given a member completes a password reset\nWhen the engine handles update_success\nThen [Code] clearAuthLockout, clearLoginCaptcha, clearTransientStrike, and clearAttempts are all invoked exactly once\nAnd [Code] clear_login_rate_limit_for_email RPC is invoked for the recovery email\nAnd [DB] login_attempts is cleared for that email\nAnd [DB] rate_limits is cleared for password_reset and login_attempt keys for that email\nAnd [UI] the next /login render shows no lockout countdown\nAnd [DB] ops_events records auth_engine.reset_succeeded',
   'manual', 'not_built'),
  ('AUTH-ENGINE-008', 'auth-rebuild', 200, 'Transient bad_jwt during bootstrap never signs out an active member',
   E'Given an active member has a valid stored session\nWhen GoTrue restarts and the first refresh returns bad_jwt once\nThen [Code] decidePurgeOnBadJwt returns purge=false on the first strike within 15s\nAnd [Code] AuthContext keeps the session and retries refreshSession\nAnd [UI] the member stays on their current screen with no flash of /login\nAnd [DB] ops_events records auth_engine.bad_jwt_transient at severity=info',
   'unit', 'not_built'),
  ('AUTH-ENGINE-009', 'auth-rebuild', 200, 'Successful sign-in emits sign_in_succeeded once and lets the screen navigate',
   E'Given a member completes sign-in (no MFA required)\nWhen the engine reaches succeeded state\nThen [Code] auth_engine.sign_in_succeeded is recorded exactly once with attempt_id and duration_ms\nAnd [UI] SignInScreen navigates to the redirect target once\nAnd [DB] audit_log shows one login_succeeded row for the attempt',
   'manual', 'not_built'),
  ('AUTH-ENGINE-010', 'auth-rebuild', 200, 'MFA required pauses the flow without ever signing the user in',
   E'Given a member with TOTP enrolled submits valid credentials\nWhen MfaService.getMfaGateDecision returns needsChallenge=true\nThen [Code] the engine transitions to mfa state and does not clear lockout/captcha\nAnd [UI] the MFA dialog opens\nAnd [DB] ops_events records auth_engine.mfa_required\nAnd [Code] navigation only fires after onMfaSuccess',
   'manual', 'not_built'),
  ('AUTH-ENGINE-011', 'auth-rebuild', 200, 'Sign-in screen never imports AuthService directly',
   E'Given the production build of SignInScreen.tsx\nWhen ripgrep scans for @/services/auth.service\nThen [Code] zero matches are found in src/features/auth/ui/SignInScreen.tsx\nAnd [Code] zero matches are found for @/lib/auth-lockout or @/lib/auth-captcha in any ui/*Screen.tsx',
   'unit', 'not_built'),
  ('AUTH-ENGINE-012', 'auth-rebuild', 200, 'Only the supabase-session adapter may import the Supabase client',
   E'Given the production source tree\nWhen the ESLint no-restricted-imports rule runs against src/features/auth/engine/**\nThen [Code] no engine file imports @/integrations/supabase/client\nAnd [Code] the only adapter allowed to import that client is supabase-session.adapter.ts',
   'unit', 'not_built'),
  ('AUTH-ENGINE-013', 'auth-rebuild', 200, 'Only the turnstile-captcha adapter touches window.turnstile',
   E'Given the production source tree\nWhen ripgrep scans for window.turnstile\nThen [Code] the only file matching is src/features/auth/adapters/turnstile-captcha.adapter.tsx (or the legacy TurnstileChallenge.tsx until Ship 5)',
   'unit', 'not_built'),
  ('AUTH-ENGINE-014', 'auth-rebuild', 200, 'CI grep guard blocks reintroduction of deleted legacy auth modules',
   E'Given Ship 5 has deleted the listed legacy modules\nWhen the check:legacy-auth-importers script runs in CI\nThen [Code] any new import of AuthService / auth-lockout / auth-captcha / auth-error-classifier / TurnstileChallenge / sign-in-password.flow / use-auth-machine fails the build',
   'unit', 'not_built'),
  ('AUTH-ENGINE-015', 'auth-rebuild', 200, 'Engine emits auth_engine.* state-transition events to ops_events',
   E'Given the auth engine processes any state transition\nWhen the audit-telemetry adapter is called\nThen [Code] record-auth-event edge function validates the kind against ALLOWED_KINDS\nAnd [DB] ops_events gains a row at severity=info with the auth_engine.* kind\nAnd [DB] the row never reaches Triage (severity:info gate)',
   'manual', 'not_built'),
  ('AUTH-ENGINE-016', 'auth-rebuild', 200, 'Post-reset sign-in within 5 minutes is never blocked by stale rate-limit',
   E'Given a member completes a password reset at T\nWhen they sign in successfully at T+30s\nThen [DB] the soak runbook query 2 returns zero rows for this email\nAnd [UI] the sign-in screen shows no lockout countdown\nAnd [DB] ops_events shows auth_engine.reset_succeeded followed by auth_engine.sign_in_succeeded with no auth_engine.sign_in_blocked in between',
   'manual', 'not_built'),
  ('AUTH-ENGINE-017', 'auth-rebuild', 200, 'Post-reset sign-in clears device lockout even if previous attempts triggered it',
   E'Given a member triggered device lockout earlier in the session\nWhen they complete a password reset and sign in\nThen [Code] clearAuthLockout is invoked on reset success\nAnd [Code] the device lockout sessionStorage key is removed\nAnd [UI] the next /login render shows no lockout',
   'manual', 'not_built'),
  ('AUTH-ENGINE-018', 'auth-rebuild', 200, 'Reset success calls clear_login_rate_limit_for_email exactly once',
   E'Given a member completes a password reset\nWhen the engine handoff runs\nThen [Code] the supabase.functions.invoke for clear_login_rate_limit_for_email is invoked exactly once with the recovery email\nAnd [DB] the rate_limits row for login_attempt:<email> is removed\nAnd [DB] subsequent sign-in attempts within the next 60s peek with allowed=true',
   'manual', 'not_built'),
  ('AUTH-ENGINE-019', 'auth-rebuild', 200, 'Forced Turnstile failure mid-sign-in recovers without page refresh',
   E'Given a member submits the sign-in form\nAnd Turnstile returns failed after the submit fires\nWhen the engine handles captcha_failed\nThen [Code] window.location is not reassigned (no full-page reload)\nAnd [UI] the form remains usable with a fresh captcha widget\nAnd [DB] ops_events records auth_engine.captcha_failed followed by auth_engine.captcha_reset within 2 seconds (soak query 3)',
   'manual', 'not_built'),
  ('AUTH-ENGINE-020', 'auth-rebuild', 200, 'Forced Turnstile failure mid-reset recovers without page refresh',
   E'Given a member submits the reset-password form\nAnd Turnstile returns failed after the submit fires\nWhen the engine handles captcha_failed\nThen [Code] no full-page reload occurs\nAnd [UI] the password fields remain populated and the captcha widget re-mounts\nAnd [DB] ops_events records auth_engine.captcha_failed and auth_engine.captcha_reset',
   'manual', 'not_built'),
  ('AUTH-ENGINE-021', 'auth-rebuild', 200, 'Stale captcha token never survives a failed submit',
   E'Given a member submits the form with a captcha token that the server rejects\nWhen the engine processes the failure\nThen [Code] setCaptchaToken("") is invoked before the next render\nAnd [Code] the next submit cannot reuse the rejected token\nAnd [UI] the user does not see "captcha already used" on the second attempt',
   'unit', 'not_built'),
  ('AUTH-ENGINE-022', 'auth-rebuild', 200, 'Single transient bad_jwt does not sign the member out',
   E'Given an active session exists\nWhen one bad_jwt strike fires inside the 15s window\nThen [Code] decidePurgeOnBadJwt returns purge=false\nAnd [Code] the client beacons reason=transient_bad_jwt\nAnd [UI] the member sees no /login redirect\nAnd [DB] ops_events records auth_engine.bad_jwt_transient',
   'unit', 'not_built'),
  ('AUTH-ENGINE-023', 'auth-rebuild', 200, 'Two bad_jwt strikes inside 15s do purge and sign out',
   E'Given an active session exists\nWhen two bad_jwt strikes fire inside the 15s window\nThen [Code] decidePurgeOnBadJwt returns purge=true on the second strike\nAnd [Code] clearLocalAuthState is invoked\nAnd [UI] the member is redirected to /login?reason=session_expired',
   'unit', 'not_built'),
  ('AUTH-ENGINE-024', 'auth-rebuild', 200, 'Soak runbook query 1: zero punitive client_session_write_failed in 24h',
   E'Given a 24-hour post-deploy window\nWhen the soak query 1 (Vichea invariant) runs against ops_events\nThen [DB] the query returns zero rows\nAnd [Code] any non-zero result blocks the rebuild from being declared Done',
   'manual', 'not_built'),
  ('AUTH-ENGINE-025', 'auth-rebuild', 200, 'Soak runbook query 2: zero post-reset still-locked loops in 24h',
   E'Given a 24-hour post-deploy window\nWhen the soak query 2 runs against ops_events\nThen [DB] the query returns zero rows (no auth_engine.sign_in_blocked within 5 minutes of auth_engine.reset_succeeded for the same email)',
   'manual', 'not_built'),
  ('AUTH-ENGINE-026', 'auth-rebuild', 200, 'Soak runbook query 3: every captcha_failed is followed by a captcha_reset within 2s',
   E'Given a 24-hour post-deploy window\nWhen the soak query 3 runs against ops_events\nThen [DB] every auth_engine.captcha_failed row has a matching auth_engine.captcha_reset within 2 seconds\nAnd [DB] the count of mismatched rows is zero',
   'manual', 'not_built'),
  ('AUTH-ENGINE-027', 'auth-rebuild', 200, 'record-auth-event rejects payloads larger than 1KB',
   E'Given a caller posts an auth_engine kind with a payload over 1024 bytes\nWhen the edge function processes the request\nThen [Code] the response status is 413\nAnd [DB] ops_events gains no row\nAnd [Code] the client adapter swallows the error and never throws',
   'unit', 'not_built'),
  ('AUTH-ENGINE-028', 'auth-rebuild', 200, 'record-auth-event rejects kinds outside the allowlist',
   E'Given a caller posts a kind that is not in ALLOWED_KINDS (for example "auth_engine.fake")\nWhen the edge function processes the request\nThen [Code] the response status is 400 with body { error: "kind_not_allowed" }\nAnd [DB] ops_events gains no row',
   'unit', 'not_built'),
  ('AUTH-ENGINE-029', 'auth-rebuild', 200, 'record-auth-event writes at severity=info so rows never reach Triage',
   E'Given any allowed auth_engine.* kind is recorded\nWhen record_event runs\nThen [DB] the ops_events row has severity=info\nAnd [Code] the discover_audit_fingerprints scanner ignores severity!=error rows\nAnd [UI] agent_fix_queue does not gain a row for the auth_engine.* event',
   'manual', 'not_built'),
  ('AUTH-ENGINE-030', 'auth-rebuild', 200, 'Telemetry failure never blocks sign-in',
   E'Given record-auth-event is unavailable (404 or network error)\nWhen the engine fires recordAuthEngineEvent during sign-in\nThen [Code] the supabase.functions.invoke promise is fire-and-forget\nAnd [Code] the engine continues to the next state without awaiting telemetry\nAnd [UI] the member completes sign-in unaffected',
   'unit', 'not_built')
ON CONFLICT (scenario_id) DO UPDATE
SET title = EXCLUDED.title,
    gherkin = EXCLUDED.gherkin,
    feature_area = EXCLUDED.feature_area,
    feature_area_number = EXCLUDED.feature_area_number,
    test_type = EXCLUDED.test_type;
