INSERT INTO public.bdd_scenarios (feature_area, feature_area_number, scenario_id, title, gherkin, status, test_type, test_file, notes) VALUES
('Authentication', 39, 'AUTH-ARCH-CUTOVER-001',
 'auth-email-hook redeployment restores reset and signup email delivery',
 E'Given the auth-email-hook had not been invoked since 2026-06-11\nAnd notify.techfleet.org is verified\nWhen the hook is redeployed and Supabase Auth send-email events fire again\nThen [Code] supabase/functions/auth-email-hook/index.ts is the deployed handler\nAnd [DB] email_send_log gains a new row with template_name in (signup, recovery) within the next attempt window\nAnd [UI] members requesting a password reset receive the branded reset email',
 'implemented', 'manual', 'supabase/functions/auth-email-hook/index.ts',
 'Root-cause fix for the Wed 6/10 - Mon 6/15 reset-email outage. incident:auth-email-hook-silent-2026-06.'),
('Authentication', 39, 'AUTH-ARCH-CUTOVER-002',
 'Legacy /reset-password/<anything> links forward to the live reset screen',
 E'Given a recovery email link points at /reset-password/<unknown-segment> with a valid token_hash query\nWhen the member clicks the link\nThen [UI] ResetPasswordScreen renders (no 404)\nAnd [Code] the splat route Route path="/reset-password/*" element={<ResetPasswordPage />} exists in src/App.tsx\nAnd [DB] ops_events records auth.recovery.token_hash.ok when the token verifies',
 'implemented', 'manual', 'src/App.tsx',
 'Preserves reset links generated before the 2026-06-11 /reset-password/confirm route landed.'),
('Authentication', 39, 'AUTH-ARCH-CUTOVER-003',
 'Forgot-password keeps anti-enumeration copy but emits typed delivery telemetry',
 E'Given a member submits a syntactically valid email through /forgot-password\nWhen the backend reset call resolves\nThen [UI] the success screen renders regardless of upstream outcome\nAnd [DB] ops_events records exactly one of auth_engine.forgot_accepted, auth_engine.forgot_email_delivery_unverified, auth_engine.forgot_rate_limited, or auth_engine.forgot_google_only_blocked\nAnd [Code] useForgotPasswordEngine never sets submitted=true without a matching telemetry event',
 'implemented', 'unit', 'src/features/auth/engine/use-forgot-password-engine.ts',
 'Closes the silent-failure class where useForgotPasswordEngine swallowed every upstream error as success. Server allowlist updated in supabase/functions/record-auth-event/index.ts.'),
('Authentication', 39, 'AUTH-ARCH-CUTOVER-004',
 'Google sign-in has exactly one entrypoint',
 E'Given the production source tree under src/ and supabase/functions/\nWhen scripts/ci/check-no-direct-google-oauth.mjs runs\nThen [Code] only src/components/GoogleSignInButton.tsx invokes the managed Google OAuth helper\nAnd [Code] supabase/functions and the rest of src/ contain zero calls to supabase.auth.signInWithOAuth with provider google\nAnd [Code] src/features/auth/flows/sign-in-google.flow.ts no longer exists\nAnd [Code] src/features/auth/adapters/supabase-session.adapter.ts no longer exports signInGoogle',
 'implemented', 'unit', 'scripts/ci/check-no-direct-google-oauth.mjs',
 'Collapses the duplicate Google OAuth paths so future Google-recover prompts cannot be blamed on stale code.'),
('Authentication', 39, 'AUTH-ARCH-CUTOVER-005',
 'CI fails if a second Google OAuth path is reintroduced',
 E'Given a pull request adds supabase.auth.signInWithOAuth(provider:"google") outside the allowed file\nWhen GitHub Actions runs the quality job\nThen [Code] scripts/ci/check-no-direct-google-oauth.mjs exits 1\nAnd [Code] .github/workflows/regression.yml runs that script before SBOM and BDD coverage\nAnd [UI] the PR check is red until the offending path is removed',
 'implemented', 'unit', '.github/workflows/regression.yml',
 'Regression gate that locks AUTH-ARCH-CUTOVER-004.'),
('Authentication', 39, 'AUTH-ARCH-CUTOVER-006',
 'Password sign-in keeps a single SDK owner under the new guard suite',
 E'Given a pull request modifies the active /login chain\nWhen the quality job runs\nThen [Code] scripts/ci/check-auth-direct-signin.mjs exits 0 only when the active sign-in chain calls signInWithPasswordService\nAnd [Code] the legacy AuthService.signInWithPassword export remains deleted\nAnd [UI] /login still renders email, password, captcha, MFA, and redirect controls unchanged',
 'implemented', 'unit', 'scripts/ci/check-auth-direct-signin.mjs',
 'Pre-existing AUTH-DIRECT-SIGNIN guard, now wired into regression.yml alongside the new Google guard.')
ON CONFLICT (scenario_id) DO UPDATE SET
  title = EXCLUDED.title, gherkin = EXCLUDED.gherkin, status = EXCLUDED.status,
  test_type = EXCLUDED.test_type, test_file = EXCLUDED.test_file,
  notes = EXCLUDED.notes, updated_at = now();