INSERT INTO public.bdd_scenarios (feature_area, feature_area_number, scenario_id, title, gherkin) VALUES
  ('Password Reset Prefetch Defense', 21, 'AUTH-RESET-PREFETCH-001', 'Recovery email links go to two-step confirm page',
   E'Feature: Recovery link prefetch defense\n  Scenario: AUTH-RESET-PREFETCH-001\n    Given a member requests a password reset\n    When auth-email-hook renders the recovery email\n    Then [Code] confirmationUrl points to /reset-password/confirm?token_hash=...&type=recovery\n    And [Code] ALLOWED_RESET_ORIGINS still constrains the host\n    And [UI] tapping the email button shows the ConfirmRecoveryLinkPage'),
  ('Password Reset Prefetch Defense', 21, 'AUTH-RESET-PREFETCH-002', 'Idempotent verify accepts an active session when the second verifyOtp fails',
   E'Feature: Recovery link prefetch defense\n  Scenario: AUTH-RESET-PREFETCH-002\n    Given the user already verified token T and holds a recovery session on this device\n    And the URL is opened a second time (back button, double-click, StrictMode remount)\n    When ResetPasswordPage calls verifyOtp(T) and it returns verify_error\n    Then [Code] confirmActiveRecoverySession() returns ok=true\n    And [Code] settle(true, "token_hash", "ok") fires\n    And [UI] the new-password form renders (no expired-link screen)\n    And [DB] no extra ops_events row marks this as a real failure'),
  ('Password Reset Prefetch Defense', 21, 'AUTH-RESET-PREFETCH-003', '/reset-password is no-store, noindex',
   E'Feature: Recovery link prefetch defense\n  Scenario: AUTH-RESET-PREFETCH-003\n    Given the production CDN serves /reset-password and /reset-password/confirm\n    When a corporate proxy or search crawler GETs the page\n    Then [Code] response carries Cache-Control: no-store, no-cache, must-revalidate, private\n    And [Code] response carries X-Robots-Tag: noindex, nofollow, noarchive, nosnippet\n    And [Code] Referrer-Policy is no-referrer\n    And [DB] no cached HTML can replay the token_hash to a different visitor'),
  ('Password Reset Prefetch Defense', 21, 'AUTH-RESET-PREFETCH-004', 'ConfirmRecoveryLinkPage never calls verifyOtp on load',
   E'Feature: Recovery link prefetch defense\n  Scenario: AUTH-RESET-PREFETCH-004\n    Given a link prefetcher GETs /reset-password/confirm?token_hash=X&type=recovery\n    When the page renders without user interaction\n    Then [Code] no supabase.auth.verifyOtp call is dispatched\n    And [Code] no supabase.auth.exchangeCodeForSession call is dispatched\n    And [DB] auth.flow_state for token X stays unconsumed\n    And [UI] only after the user clicks Continue resetting password does navigation to /reset-password fire verifyOtp'),
  ('Password Reset Prefetch Defense', 21, 'AUTH-RESET-PREFETCH-005', 'Expired/burned link surfaces actionable Send a new link CTA',
   E'Feature: Recovery link prefetch defense\n  Scenario: AUTH-RESET-PREFETCH-005\n    Given verifyOtp returns verify_error AND confirmActiveRecoverySession returns ok=false\n    When ResetPasswordPage settles\n    Then [Code] linkExpired is set to true\n    And [Code] settleInvalid token_hash verify_error emits the recovery telemetry beacon\n    And [UI] heading reads This reset link cant be used\n    And [UI] body explains single-use semantics in plain language\n    And [UI] primary CTA is Send a new reset link linking to /forgot-password')
ON CONFLICT (scenario_id) DO UPDATE
  SET title = EXCLUDED.title,
      gherkin = EXCLUDED.gherkin,
      feature_area = EXCLUDED.feature_area,
      feature_area_number = EXCLUDED.feature_area_number,
      updated_at = now();