// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // AUTH-RESET fix: prevent AuthContext's bootstrap getSession() from
    // auto-consuming the recovery hash/code before ResetPasswordPage's
    // onAuthStateChange subscriber attaches. ResetPasswordPage now consumes
    // recovery params explicitly via verifyOtp/exchangeCodeForSession.
    // Google OAuth still works because we drive it via exchangeCodeForSession
    // on the callback route, not via auto-detect.
    detectSessionInUrl: false,
  }
});